@startuml Feature 2.1

'''' Declarations to stylize the diagram '''
hide circle
hide empty members
allowmixing

!theme mars
skinparam classFontStyle bold
skinparam classAttributeIconSize 0
skinparam noteBackgroundColor wheat

'''' Work Items ''''
object "(1) Feature 2.1" as Feature2_1

object "(2) V Requirement 1" as VRequirement1
object "(3) V Task 1" as VTask1
note right : commit 1

object "(4) Test Case 1" as TestCase1

object "(5) V Requirement 2" as VRequirement2
object "(6) V Task 2" as VTask2
note right : commit 2

'''' Work IteIDs ''''
Feature2_1     : #374352
VRequirement1  : #374354
VTask1         : #374357
TestCase1      : #374356
VRequirement2  : #374355
VTask2         : #374358

Feature2_1    -right- VRequirement1 : <
VRequirement1 -       VTask1        : <
Feature2_1    -right- VRequirement2 : <
VRequirement2 -       VTask2        : <

VRequirement2  "Successor"  -up-   "Predecessor" VRequirement1 : replaced by <
TestCase1      "TestedBy"   -down- "Tests"       VRequirement1 : tested by <

@enduml
