function Export-ReleaseNotesFromTfvcToExcel {

    <#
        .SYNOPSIS
            Runs compilation of release notes data from TFVC based project.

        .PARAMETER CollectionUri
            Url for project collection on Azure DevOps server instance.
            Can be ommitted if $CollectionUri was previously accessed via this API.
            If not specified, $global:AzureDevOpsApi_CollectionUri (set by Set-AzureDevopsVariables) is used.

        .PARAMETER Project
            Project name, identifier, full project URI, or object with any one
            these properties.
            Can be ommitted if $Project was previously accessed via this API (will be extracted from the $ArtifactUri).
            If not specified, $global:AzureDevOpsApi_Project (set by Set-AzureDevopsVariables) is used.

        .PARAMETER DateFrom
            Starting date for the considered Changesets.

        .PARAMETER DateTo
            Ending date for the considered Changesets.

        .PARAMETER AsOf
            Gets the Work Items as they were at this date and time.

        .PARAMETER ByUser
            User(s) whose Changesets will be used.

        .PARAMETER TrunkBranch
            Trunk branch. The $DateFrom and $DateTo will be used to filter the
            Changesets on this branch.

        .PARAMETER ReleaseBranch
            Release branch. All Changesets on this branch will be considered.

        .PARAMETER Show
            Flag, whether open the exported document.

        .PARAMETER PassThru
            Flag, whether return the generated file.

        .PARAMETER UseConstantFileName
            Flag, whether to use constant file name.
            If $Path is a directory, the file will be named "ReleaseNotes.xlsx"
            Ignored if $Path is a filename.

        .PARAMETER Path
            Path or filename for the exported data to be saved to.
            If not specified, the file will be saved to the current directory.
            If points to a directory and $UseConstantFileName is specified,
            the file will be named "ReleaseNotes.xlsx", otherwise the filename
            will be "ReleaseNotes_$Project_$CreatedOnDateTime.xlsx".

        .PARAMETER TimeZone
            All times from AzureDevOps API are in UTC.
            Parameter determines the time zone all date times will be converted to.

            Uses .net TimeZoneInfo class to resolve and calculate the date times.

            Possible values are:
            IANA style zone ids, f.e. "Europe/Bratislava"
            Windows style zone ids, f.e. "Central Europe Standard Time"

            Default value is "Central Europe Standard Time".

        .PARAMETER ProgressPreference
            Determines how PowerShell responds to progress updates generated by a script,
            cmdlet, or provider, such as the progress bars generated by the Write-Progress
            cmdlet.

        .PARAMETER TimePeriodWorkItemsFilter
            Filter to be used on acquired work items. Included are only passing ones.
    #>

    [CmdletBinding()]
    param(
        [AllowNull()]
        [AllowEmptyString()]
        $CollectionUri,

        [AllowNull()]
        [AllowEmptyString()]
        $Project,

        [Alias('FromDate', 'From')]
        [Nullable[DateTime]] $DateFrom,

        [Alias('ToDate', 'To')]
        [Nullable[DateTime]] $DateTo,

        [Nullable[DateTime]] $AsOf,

        $ByUser,

        $TrunkBranch = 'Trunk',

        [AllowNull()]
        [AllowEmptyString()]
        [string] $ReleaseBranch,

        $Path = '.\',

        [string] $TimeZone = 'UTC',

        [switch] $Show,
        [switch] $PassThru,

        [switch] $UseConstantFileName,

        [System.Management.Automation.ActionPreference] $ProgressPreference = $PSCmdlet.GetVariableValue('ProgressPreference'),

        [Alias('TimePeriodFilter')]
        [scriptblock] $TimePeriodWorkItemsFilter
    )

    # Show start message
    Show-Host -ForegroundColor Cyan -Object 'Release list export started'

    # Report back provided parameters
    Show-Host -ForegroundColor Magenta -Object 'Provided parameters'

    # Correct paramater values
    $DateFrom = Use-FromDateTime -DateFrom $DateFrom
    $DateTo = Use-ToDateTime -DateTo $DateTo
    $AsOf = Use-AsOfDateTime -AsOf $AsOf -DateTo $DateTo
    $TrunkBranch = Use-Value -A $TrunkBranch -B 'Trunk'
    $Project = Use-Project -Project $Project

    # Show input parameters
    Show-Parameters -Parameters $MyInvocation.BoundParameters

    # Coolect data from TFVC
    $data = Get-ReleaseNotesDataFromTfvc `
        -Collection $CollectionUri `
        -Project $Project `
        -DateFrom $DateFrom `
        -DateTo $DateTo `
        -AsOf $AsOf `
        -ByUser $ByUser `
        -TrunkBranch $TrunkBranch `
        -ReleaseBranch $ReleaseBranch `
        -TimePeriodWorkItemsFilter $TimePeriodWorkItemsFilter

    # Prepare the data for export
    Show-Host -ForegroundColor Magenta -Object 'Preparing Work Item Data for export...'
    $exportData = ConvertTo-ExportData `
        -ItemsTable $data `
        -Collection $CollectionUri `
        -Project $Project `
        -DateFrom $DateFrom `
        -DateTo $DateTo `
        -AsOf $AsOf `
        -ByUser $ByUser `
        -TrunkBranch $TrunkBranch `
        -ReleaseBranch $ReleaseBranch

    # Export the data
    Show-Host -ForegroundColor Magenta -Object 'Exporting Data...'
    $outputFile = AzureDevOpsApi\Export-Excel `
        -ExportData $exportData `
        -Path $Path `
        -TimeZone $TimeZone `
        -UseConstantFileName:$UseConstantFileName `
        -Show:$Show `
        -PassThru:$true

    # Report the file path
    ([PSCustomObject] @{ ExportedTo = $outputFile.FullName }) | Format-List | Out-Host

    # Return the output file
    if ($PassThru) {
        return $outputFile
    }
}

Set-Alias -Name Export-ReleaseNotesFromTfvc -Value Export-ReleaseNotesFromTfvcToExcel
